### ISSUE TITLE
Should we have aggregations across trips and stops?

### ISSUE THREAD

**Issue by e-lo** [osplanning-data-standards/GTFS-STAT#4]
Right now the files are set up to have aggregation variables (time periods; date ranges, etc) for both trips and stops, but there aren't any aggregation fields...rather it looks like it is designed for raw data.  If it is just raw data, shouldn't the file directly mimic stop_times.txt and trips.txt but with the addition of a date?

**Comment by sdrewc** [comment]
Closed by #7
